name: Auto Update README
on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-readme:
    name: Auto Update README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Make Changes to README
        run: |
          echo "Making changes to README.md..."
          # Add a space to the end of README.md 
          echo " " >> README.md
          # Configure Git
          git config --global user.name "README Update Bot"
          git config --global user.email "readme-update-bot@example.com"
          # Commit the changes
          git add README.md
          git commit -m "chore: auto-update README"

      - name: Push Changes
        run: |
          git push
