name: Auto-Update README

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Toggle Marker in README
        run: |
          if grep -q "AUTO-SPACE" README.md; then
            # Remove the marker if it exists
            sed -i '/AUTO-SPACE/d' README.md
          else
            # Add the marker if it doesn't exist
            echo "AUTO-SPACE" >> README.md

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Auto-update README: Toggled space marker"
          git push
